### ISSUE TITLE
Homepage Cover, Fonts, Stretched Photos, EXECs page  

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#1]
- I think its best if we use the regular logo over the animation on the front page
- Use fonts related to our logo (in reference to the titles on each page) (fonts in google drive)
- Quad kit optional extras need to be products in the store (ill get you prices)
- Some photos are stretched, so we may need to update some so they fit 
- For past create execs, maybe make a separate page and put a hyperlink to it

**Comment by NoOne2246** [comment]
The current team page photos on the right hand side people are misaligned on Chrome.

**Comment by cjoy** [comment]
@NoOne2246 Yeah, it seems like the text wrap changes the  height of the profile pods. I'll set a constant height for that pod and it should be fixed. Thanks for noticing this!

**Comment by cjoy** [comment]
@Anthony-1811 We may need to change most of the cover photos for each page. I used randomly selected ones from the Facebook page.
