### ISSUE TITLE
Veroboard pricing

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#12]
![image](https://cloud.githubusercontent.com/assets/11746039/23574479/d7008078-00d2-11e7-9a5f-ad236a4368ab.png)

The pricing is different for each style. A dropdown menu may be required.

**Comment by Anthony-1811** [comment]
![image](https://cloud.githubusercontent.com/assets/11746039/23574520/3260b0e6-00d3-11e7-8bee-55b1d5cedbaa.png)
Same thing here

**Comment by Anthony-1811** [comment]
![image](https://cloud.githubusercontent.com/assets/11746039/23574530/4a3dc4b0-00d3-11e7-9e67-4a5a51683c06.png)
and here, we need different cart options as it prevents confusion when we process orders

**Comment by Anthony-1811** [comment]
![image](https://cloud.githubusercontent.com/assets/11746039/23574543/765904ec-00d3-11e7-8770-aeca54b4813e.png)
This should be two separate products

**Comment by Anthony-1811** [comment]
![image](https://cloud.githubusercontent.com/assets/11746039/23574570/cc751186-00d3-11e7-9003-f2ec1e35ebc8.png)
this is missing, Straight Male-Male Header  $0.20

**Comment by Anthony-1811** [comment]
![image](https://cloud.githubusercontent.com/assets/11746039/23574592/f09f1f48-00d3-11e7-96d5-03c42b0e40b1.png)
here as well. Maybe its worth splitting this one into separate items because the items are different styles

**Comment by cjoy** [comment]
@will-weng

**Comment by Anthony-1811** [comment]
Other items have not been fixed yet
