### ISSUE TITLE
Add column spacing to past-exec table

### ISSUE THREAD

**Issue by nathanja** [CreateUNSW/createunsw.github.io#15]
So people with longer names don't run into the right column

**Comment by cjoy** [comment]
seems like it's fixed.

**Comment by nathanja** [comment]
Nah - like Alex Yellachich runs right into the next column for example. I'd attach a photo here from mobile if I could, but if you need more explanation ask me

**Comment by Gnahz3640** [comment]
It doesn't do it on my phone. Or is this desktop version we're talking about?

**Comment by cjoy** [comment]
This table was going to be removed and replaced with a new dynamic team profile page. 
However nobody has uploaded their profile files to the GDrive, found here:
https://drive.google.com/drive/u/0/folders/0B4V3sdsANIHqR2JoSVlHcC1kSzQ

The new dynamic team profile page offers the following new features:
- allows us to add and archive members easily
- allows us to show case the achievements, projects etc, of members (kind of like a bio/about-me section)
- generates a custom page for each team member (with a cover page, changeable profile picture, optional social media and contact links etc)

**Comment by nathanja** [comment]
I think we should have somewhere already photos of old exec. This goes years back so it's unlikely you'll get old exec to fill out all this stuff, at least not immediately.

I think dynamically it should be able to handle a photo and nothing else if no other content is provided, we should be able to scrape photos together.

They are somewhere in the pre-hales old website in image assets? I can dig these up later

**Comment by cjoy** [comment]
Yeah, I got most of the old exec photos. I'll just create generic profiles for the execs and if they wish to add stuff to their profile, they can just add it via github or add a custom file to the google drive.
