### ISSUE TITLE
Wrong pictures for basics kit

### ISSUE THREAD

**Issue by Veyrdite** [CreateUNSW/createunsw.github.io#19]
http://www.createunsw.com.au/store/basics-kit/

Picture shows something much more expensive, completely different parts.

**Comment by Excelray1** [comment]
Agreed

**Comment by cjoy** [comment]
Does anybody know where I can obtain an image for the basic kit?

**Comment by Gnahz3640** [comment]
The basic kits just got delivered last week. Will send an updated picture your way on Monday :)
