### ISSUE TITLE
Create logo not centred on front page on chrome

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#2]
<img width="1908" alt="screen shot 2017-02-28 at 10 41 59 am" src="https://cloud.githubusercontent.com/assets/11746039/23385217/b8ef3de6-fda2-11e6-9cce-1ab388384cee.png">

Maybe make it larger as well?

**Comment by cjoy** [comment]
Yeah, thanks for picking up on this. I'll fix it up asap.
