### ISSUE TITLE
hales' name on uas blog 

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#20]
![image](https://cloud.githubusercontent.com/assets/11746039/23854373/401c93de-0845-11e7-8990-a1d4978700dc.png)

**Comment by cjoy** [comment]
Not sure who initially wrote the post. Feel free to change the author in the _media folder. 

Thanks

**Comment by Gnahz3640** [comment]
All good! I know how to update it (though I'll only update the ones I know)
