### ISSUE TITLE
Incorrectly named sales item: "Uno kit"

### ISSUE THREAD

**Issue by Veyrdite** [CreateUNSW/createunsw.github.io#28]
Both the $45 and $50 kits are called the 'comprehensive kits' in internal lingo.  One is the comprehensive with a mega, the other is the comprehensive with an uno.

"uno kits" might get confused with the smaller kits, and people might get the wrong stuff.

**Comment by cjoy** [comment]
Thanks for the clarification!

I'll fix it up right now. 

Your contributions are much appreciated :)

**Comment by cjoy** [comment]
@Veyrdite I've renamed it to Uno and Mega kits. Let me know if you would prefer for it to be renamed something else, before a close this issue. Thanks
