### ISSUE TITLE
New Stock!!!

### ISSUE THREAD

**Issue by lam5ter** [CreateUNSW/createunsw.github.io#30]
https://scontent-sjc2-1.xx.fbcdn.net/v/t35.0-12/18261096_1879228495436012_1187553086_o.jpg?oh=278e83e7515d25f8c096b4fc1dbe6f51&oe=59083A86
https://scontent-sjc2-1.xx.fbcdn.net/v/t35.0-12/18235799_1879228498769345_1181698296_o.jpg?oh=199ca1856950ea53b8d9598dd51821f2&oe=59076
Pictures for new stock.
- Wire cutters/strippers - $7.50
- Buck (LM2596) and Boost (LM2577) Modules - $5

**Comment by cjoy** [comment]
Hey @lam5ter, I don't have access to view the second image, This may have something to do with facebook's cdn permission system.
