### ISSUE TITLE
Event Engineering logo broken

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#35]
![image](https://cloud.githubusercontent.com/assets/11746039/26181830/95b5a278-3bb6-11e7-9cb7-08cf7d6c06cb.png)

**Comment by Gnahz3640** [comment]
![ee_logo_final](https://cloud.githubusercontent.com/assets/5714228/26710749/b996923e-479f-11e7-8c21-9c1d37a95536.png)
Maybe try replace the .eps file with this .png file? I'm not sure how to replace it though... @MrChrisJoy
