### ISSUE TITLE
Wrong kit price change

### ISSUE THREAD

**Issue by lam5ter** [CreateUNSW/createunsw.github.io#39]
The Uno Kit should be the same price. Supposed to change Arduino Uno Basic Kit to $25 (was $20).

**Comment by cjoy** [comment]
Oh okay, the product files are over here
https://github.com/CreateUNSW/createunsw.github.io/tree/master/_products

Feel free to make changes :)

**Comment by cjoy** [comment]
I assume this is fixed.
