### ISSUE TITLE
On the "About" page

### ISSUE THREAD

**Issue by Gnahz3640** [CreateUNSW/createunsw.github.io#4]
The banner says "Built, Learn, Inspire" rather than "Build, Learn, Inspire"

Also, we don't run Hackerspace at A&D anymore... but that's more of a website content issue though I guess?

**Comment by cjoy** [comment]
@Gnahz3640 
What do you mean by:
             The banner says "Built, Learn, Inspire" rather than "Build, Learn, Inspire"
I've deleted the hackerspace part from the events and about page.

Thanks for picking up on this.

**Comment by Gnahz3640** [comment]
Oh... someone changed it to STUDENT-LED / PROJECT STARTERS / MAKER CLUB after I made the comment. Don't worry about it. :)
