### ISSUE TITLE
Team update

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#43]
Abi is no longer the team lead. It's me.
![image](https://user-images.githubusercontent.com/11746039/33295442-7e8c27dc-d429-11e7-8855-5a292b9ffb9e.png)

Also can we had Junji, Jono and William (art & design) as Vivid co leads, Jabez as DRC lead and Randy as UGV lead.

**Comment by cjoy** [comment]
Yep, I'll update this soon. Do you happen to have photos for Juni, Jono, Jabez and Randy?

**Comment by Anthony-1811** [comment]
Just hold up on this

**Comment by Anthony-1811** [comment]
@mrchrisjoy so put Junji, Jono and William (art & design) as Project Illuminate co-leaders
