### ISSUE TITLE
About us update

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#44]
![image](https://user-images.githubusercontent.com/11746039/33295527-f519b28e-d429-11e7-9fa2-09e43b4e1791.png)

Can we update the last paragraph to this:
CREATE currently has a membership of over 2000 students. The club was awarded Arc Club of the Year in 2013 and 2015, as well as, Arc Regular Club of the Year 2017 and Arc Best Off-campus Activity for Crystallise 2017. In 2015, current president and founding member Nathan Adler, founding president Sam Cassisi and another founder Austin Kong were recognized by the UNSW Faculty of Engineering with Student Service Awards for their contributions to the UNSW community through CREATE.

**Comment by cjoy** [comment]
Will do! Thanks for the update.
