### ISSUE TITLE
Urgent Request for a project dedicated tab

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#46]
![file 28-11-17 11 11 59 am](https://user-images.githubusercontent.com/11746039/33296168-f6689f02-d42d-11e7-8573-83effd9a5ecf.jpeg)
![file 28-11-17 11 18 48 am](https://user-images.githubusercontent.com/11746039/33296173-fa7e5136-d42d-11e7-8f96-88213025eba6.jpeg)
Please do this as quickly as possible I want it for when I target sponsors. Let me know if you have any questions @mrchrisjoy

**Comment by Anthony-1811** [comment]
We should keep the media tab for newsletters, youtube live vids, workshop slides and CREATE in the media stuff.

**Comment by cjoy** [comment]
Sounds feasible. I'll do it ASAP.
