### ISSUE TITLE
Profile pics in team section now super cropped and weird

### ISSUE THREAD

**Issue by nathanja** [CreateUNSW/createunsw.github.io#47]
Came back to the team page recently to note that the design has changed. I understand getting rid of circles, but cropping everyone's head into a landscape rectangle isn't a good look.

**Comment by cjoy** [comment]
Good pickup. I didn't noticed that. Will fix it up soon.

**Comment by Anthony-1811** [comment]
bump

**Comment by cjoy** [comment]
I've reduced the width of each card. Looks a bit better than before. Feel free to reopen if there's still a problem.
