### ISSUE TITLE
NSW Gov logo

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#55]
Can we please put the NSW gov logo as one of our sponsors:
http://bluesat.com.au/wp-content/uploads/2016/10/nswgov-sponsor-300x144.png

make sure its linked to this website: https://www.nsw.gov.au/improving-nsw/premiers-priorities/

**Comment by Anthony-1811** [comment]
@mrchrisjoy can you put this up asap, its a part of our agreement with NSW gov.

**Comment by cjoy** [comment]
Yep, I'll add it tonight.
