### ISSUE TITLE
Suggestion: Media and/or profiles about past exec + members

### ISSUE THREAD

**Issue by nathanja** [CreateUNSW/createunsw.github.io#6]
Left-field but I think worthwhile:

Either a section in the website or otherwise integrated content about what current and past highly involved CREATE members are up to. A number of ex-CREATE members out there running their own start-ups, doing well in their careers, working with hands-on technology professionally.

Would require some planning!

@Anthony-1811

**Comment by cjoy** [comment]
Great Idea! 

I got something in my mind and I will implement it as soon as I am free.

I'll keep this issue open, until I finish implementing it.
